server:
    port: 8080
    servlet:
        context-path: /bootcamp


spring.main.allow-circular-references: true

spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 123456
    jpa:
        show-sql: true
        database-plataform: org.hibernate.dialect.PostegreSQLDialect
        generate-ddl: true
        hibenate:
            ddl-studio: none